id: IF455562A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-14T10:00:39+00:00'
last_modified: '2022-06-15T16:47:37.937130+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10250
  title: ཧོར་གླིང་བསྡུས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    FF82:
      image_group_id: I1KG10252
      title: Volume 1 of hor gling bsdus pa/
      total_pages: 426
      order: 1
      base_file: FF82.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
